# Generated by Django 5.2 on 2025-07-19 13:20

import config.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Friendly name for this source (e.g., 'Production DB')", max_length=100)),
                ('type', models.CharField(choices=[('database', 'Database'), ('volume', 'Volume')], help_text='Type of backup source', max_length=20)),
                ('db_type', models.CharField(blank=True, choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL/MariaDB'), ('sqlite', 'SQLite')], help_text='Database type (required if source type is Database)', max_length=20, null=True)),
                ('db_host', models.CharField(blank=True, help_text='Database host', max_length=255)),
                ('db_port', models.PositiveIntegerField(blank=True, help_text='Database port', null=True)),
                ('db_name', models.CharField(blank=True, help_text='Database name', max_length=100)),
                ('db_user', models.CharField(blank=True, help_text='Database username', max_length=100)),
                ('db_password', config.fields.EncryptedCharField(blank=True, help_text='Database password', max_length=500)),
                ('volume_name', models.CharField(blank=True, help_text='Docker volume name (required if source type is Volume)', max_length=100)),
            ],
            options={
                'db_table': 'sources',
                'ordering': ('-created_at',),
            },
        ),
    ]
