# Generated by Django 5.2 on 2025-07-19 13:20

import config.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Friendly name for this destination (e.g., 'My Project Channel')", max_length=100)),
                ('telegram_bot_token', config.fields.EncryptedCharField(help_text='Telegram bot API token', max_length=500)),
                ('telegram_channel_id', config.fields.EncryptedCharField(help_text='Telegram channel ID or username', max_length=200)),
            ],
            options={
                'db_table': 'destinations',
                'ordering': ('-created_at',),
            },
        ),
    ]
