# Generated by Django 5.2 on 2025-07-19 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.CharField(help_text="Cron expression for scheduling (e.g., '0 2 * * *' for daily at 2 AM)", max_length=100)),
                ('output_format', models.CharField(choices=[('sql', '.sql'), ('tar.gz', '.tar.gz')], default='tar.gz', help_text='Output format for backup files', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this backup job')),
                ('destination', models.ForeignKey(help_text='Destinations for backup files', on_delete=django.db.models.deletion.CASCADE, to='destinations.destinations')),
                ('source', models.ForeignKey(help_text='Sources to backup', on_delete=django.db.models.deletion.CASCADE, to='sources.sources')),
            ],
            options={
                'db_table': 'backup_jobs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExecutionLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('success', 'SUCCESS'), ('failed', 'FAILED')], help_text='Execution status', max_length=10)),
                ('details', models.TextField(blank=True, help_text='Execution details, output messages, or error information')),
                ('file_size', models.PositiveBigIntegerField(blank=True, help_text='Size of the generated backup file in bytes', null=True)),
                ('job', models.ForeignKey(help_text='The backup job this log entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='jobs.backupjobs')),
            ],
            options={
                'db_table': 'execution_logs',
                'ordering': ('-created_at',),
            },
        ),
    ]
